### ISSUE TITLE
Call the `renovate` workflow from any GitHub user or organization

### ISSUE THREAD

**Issue by marcusrbrown** [bfra-me/renovate-config#467]
Currently, the `renovate` workflow requires a GitHub App (see [self-hosted Renovate](https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app)) to run. This limits callers to those that can pass a GH App ID and private key. The workflow should be modified to allow for a PAT and not assume it's being called from an organization account (i.e., when acquiring the workflow token from the GitHub App).

Depends on #466 - callers of the workflow need to be able to pin to a specific release tag.

- [X] ~~Use a non-default `RENOVATE_BRANCH_PREFIX` to avoid issues with the Mend Renovate App _Resolved in #468_~~
- [X] Don't acquire application tokens from an organization installation if a user account called the workflow _Resolved in #471_
- [X] Add `git_author` and `username` inputs to `workflow_call` trigger in the `renovate` workflow _Resolved in #498_

**Comment by marcusrbrown** [comment]
Closed by #498 and #471.
